### PR TITLE
Add readme, test, update dependencies

### PR DESCRIPTION
**Pull request by finnp**
Hey,

I created a readme for this module and a small test. I also updated the level dependencies, because I was getting install errors with the versions you were using.

Best,
Finn

### CODE REVIEW

**Comment by mikeal** [comment]
thanks! you are now a collaborator.

**Comment by finnp** [comment]
Thanks :+1: If you add me (finnpauls) on npm, I'll also publish a new version

**Comment by mikeal** [comment]
it says there isn’t a finnp user :(

**Comment by finnp** [comment]
It's `finnpauls` not `finnp`. It' stupid to have different usernames there, but changing usernames also sucks.

**Comment by mikeal** [comment]
done :)

**Pull request merged**
